# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Use official Node.js LTS on Alpine
FROM node:lts-alpine

WORKDIR /app

# Install dependencies (including dev for build)
COPY package.json package-lock.json ./
RUN npm install

# Copy remaining source files
COPY . .

# Build the project
RUN npm run build

# Entrypoint for MCP server
CMD ["bun", "run", "dist/index.js", "--transport", "http", "--port", "3100", "--host", "0.0.0.0"]
